/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsparams = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AmplifyWebApp",
            "endpoint": "https://ltjbory0m0.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jVNJLO2bk",
    "aws_user_pools_web_client_id": "3qduue93flmhs2kb537pcrvjo2",
    "oauth": {},
    "app_linking": {
        "COGNITO_AUTH_URL": 'Value for your Cognito Authorization URL',
        "LWA_CLIENT_ID": 'Value for LWA Client ID',
        "COGNITO_ALEXA_APP_CLIENT_ID": 'Value for Cognito Alexa App Client ID',
        "WEB_APP_URL": 'Value for Web App URL'
    }
};


export default awsparams;
